CREATE TABLE `bill_base_transaction_mapping` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Bill_details_id` int(10) unsigned NOT NULL,
  `Doc_Date` date NOT NULL,
  `Posting_Date` date NOT NULL,
  `Provision_Document_Number` char(10) NOT NULL,
  `Fiscal_year` char(4) NOT NULL,
  `Provision_Document_Item` int(3) unsigned NOT NULL,
  `Internal_order` char(12) NOT NULL,
  `Base_Transaction_Type` char(15) NOT NULL,
  `Base_Transaction_Date` date NOT NULL,
  `Base_Transaction_Number` char(25) NOT NULL,
  `Customer_Code` char(10) DEFAULT NULL,
  `Amount_Provisional` double NOT NULL,
  `Amount` double NOT NULL,
  `Created_On` date NOT NULL,
  `Created_By` int(10) unsigned NOT NULL,
  `is_tagged_to_invoice` tinyint(1) DEFAULT '0',
  `GL_Number` varchar(45) DEFAULT NULL,
  `is_reversed` int(11) DEFAULT '0',
  `reversed_date` datetime DEFAULT NULL,
  `bill_internal_order_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_bill_base_transaction_mapping_billId` (`Bill_details_id`),
  CONSTRAINT `FK_bill_base_transaction_mapping_billId` FOREIGN KEY (`Bill_details_id`) REFERENCES `billdetails` (`BillDetails_ID`)
) ;