CREATE TABLE `sap_payment_details` (
  `sap_payment_details_id` int(11) NOT NULL AUTO_INCREMENT,
  `CO_CODE` varchar(4) DEFAULT NULL,
  `FISC_YEAR` varchar(4) DEFAULT NULL,
  `GL_ID` varchar(10) DEFAULT NULL,
  `POST_DATE` date DEFAULT NULL,
  `DOC_DATE` date DEFAULT NULL,
  `REFERENCE` varchar(16) DEFAULT NULL,
  `HEADER_TEXT` varchar(25) DEFAULT NULL,
  `DOC_TYPE` varchar(2) DEFAULT NULL,
  `DOC_NO` varchar(10) DEFAULT NULL,
  `DOC_ITEM_NO` varchar(3) DEFAULT NULL,
  `VEN_CODE` varchar(10) DEFAULT NULL,
  `RECON_GL` varchar(10) DEFAULT NULL,
  `BASE_DATE` date DEFAULT NULL,
  `PROFIT_CENTER` varchar(10) DEFAULT NULL,
  `AMT_TRANS` decimal(23,0) DEFAULT NULL,
  `CURRENCY` varchar(3) DEFAULT NULL,
  `SPECIAL_GL` varchar(1) DEFAULT NULL,
  `BUPLA` varchar(4) DEFAULT NULL,
  `TEXT` varchar(50) DEFAULT NULL,
  `ASSIGNMENT` varchar(18) DEFAULT NULL,
  `ENTRY_DATE` date DEFAULT NULL,
  `INV_REFERENCE` varchar(10) DEFAULT NULL,
  `INV_REF_FY` varchar(4) DEFAULT NULL,
  `CLEAR_DOC_NO` varchar(10) DEFAULT NULL,
  `CLEAR_FY` varchar(4) DEFAULT NULL,
  `CLEAR_DATE` date DEFAULT NULL,
  `audit_log_id` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  PRIMARY KEY (`sap_payment_details_id`),
  UNIQUE KEY `sap_payment_details_id_UNIQUE` (`sap_payment_details_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1