CREATE TABLE `vendor_invoice` (
  `vendor_invoice_id` int(11) NOT NULL AUTO_INCREMENT,
  `event` varchar(3) NOT NULL,
  `src_sys` varchar(25) NOT NULL,
  `trn_batchid` varchar(20) NOT NULL,
  `co_code` varchar(4) NOT NULL,
  `doc_date` date NOT NULL,
  `reference` varchar(16) NOT NULL,
  `post_date` date NOT NULL,
  `currency` varchar(10) NOT NULL,
  `invoice_amount` double NOT NULL,
  `vendor_code` varchar(10) NOT NULL,
  `alternate_recon_gl` varchar(10) DEFAULT NULL,
  `business_place` varchar(4) NOT NULL,
  `base_date` date NOT NULL,
  `withholding_type` varchar(2) DEFAULT NULL,
  `withholding_code` varchar(2) DEFAULT NULL,
  `withholding_tax_base` double DEFAULT NULL,
  `exchange_rate` double DEFAULT NULL,
  `line_item` int(10) NOT NULL,
  `gl_id` double NOT NULL,
  `item_text` varchar(50) DEFAULT NULL,
  `internal_order` varchar(12) DEFAULT NULL,
  `cost_center` varchar(10) DEFAULT NULL,
  `basetrans_type` varchar(12) NOT NULL,
  `base_transaction` varchar(22) NOT NULL,
  `base_transaction_date` date NOT NULL,
  `quantity` double DEFAULT NULL,
  `unit_of_measurement` varchar(45) DEFAULT NULL,
  `tax_code` varchar(2) NOT NULL,
  `assignment` varchar(18) DEFAULT NULL,
  `hsn_code` varchar(16) NOT NULL,
  `payment_method` varchar(10) NOT NULL,
  `transaction_amount` double NOT NULL,
  `purchase_order` varchar(45) DEFAULT NULL,
  `po_line_item` int(10) DEFAULT NULL,
  `vendor_code2` varchar(45) NOT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `updated_by` varchar(45) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `bill_details_id` int(10) unsigned DEFAULT NULL,
  `bill_internal_order_id` int(10) unsigned DEFAULT NULL,
  `doc_type` varchar(45) DEFAULT NULL,
  `payment_term` varchar(45) DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`vendor_invoice_id`),
  KEY `fk_bill_details_id_vendor_idx` (`bill_details_id`),
  KEY `fk_bill_internal_order_id_vendor_idx` (`bill_internal_order_id`),
  CONSTRAINT `fk_bill_details_id_vendor` FOREIGN KEY (`bill_details_id`) REFERENCES `billdetails` (`BillDetails_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_internal_order_id_vendor` FOREIGN KEY (`bill_internal_order_id`) REFERENCES `bill_internal_order_mapping` (`Internal_order_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1  